name: Gyurus Docs - Node Build
description: Install + build the Docusaurus site

inputs:
  working-directory:
    description: Path to the Docusaurus project
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run build
