name: Gyurus Docs - Docker Build & Push
description: Build and push the Docker image to GHCR

inputs:
  image-name:
    description: Full image name (ghcr.io/owner/name)
    required: true
  context:
    description: Docker build context
    required: false
    default: .
  dockerfile:
    description: Path to Dockerfile
    required: false
    default: Dockerfile

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=raw,value=latest-tag

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
