name: gyurus-docs

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  # GHCR image names must be lowercase; repository_owner is already lowercase.
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/gyurus-docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docusaurus
        uses: ./gyurus-docs/.github/actions/docs-build

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & push image to GHCR
        uses: ./gyurus-docs/.github/actions/docs-docker
        with:
          image-name: ${{ env.IMAGE_NAME }}

  # Optional: remote deploy over SSH.
  # Add these repository secrets to enable:
  # - DEPLOY_HOST, DEPLOY_USER, DEPLOY_SSH_KEY
  # And ensure the server has a docker-compose.yml at DEPLOY_PATH.
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ github.ref == 'refs/heads/main' && secrets.DEPLOY_HOST != '' }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            cd "${DEPLOY_PATH:-/opt/gyurus-docs}"
            docker compose pull
            docker compose up -d
